# Generated by Django 5.0.6 on 2024-11-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_madule', '0004_productcategory_alter_product_slug_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=300, verbose_name='رنگ')),
                ('size', models.CharField(max_length=300, verbose_name='سایز')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_inforamtion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_madule.productinformation', verbose_name='اطلاعات'),
        ),
    ]
